apiVersion: v1
kind: Pod
metadata:
  name: my-jenkins
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:2.303.1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "name"
                operator: NotIn
                values:
                  - worker
